Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 22, host: 2202, host_ip: "127.0.0.1"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    # Installation de Nginx
    echo "Y" | sudo apt-get install -y nginx
  SHELL
end
